### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by enexusde** [forestryio/forestry.io#230]
Calling NPM install breaks.

```
WARN engine css-blank-pseudo@0.1.4: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
npm ERR! Linux 4.4.0-189-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolve
[npm-debug.log](https://github.com/forestryio/forestry.io/files/5231016/npm-debug.log)
WithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/forestry.io/npm-debug.log
root@xxx:~/forestry.io# npm install
```

**Comment by DirtyF** [comment]
Hi, I don't know what you're trying to do here, but looks like you need to install node 12

**Comment by enexusde** [comment]
I try to run the app on a server.

**Comment by DirtyF** [comment]
This is our website, not our app, it's not open source.

**Comment by enexusde** [comment]
Ok
